language: python
python:
  - "3.8"
script:
  - pip3 install ms_peak_picker
  - pip3 install Cython --upgrade
  - pip3 install pandas numpy --upgrade
  - pip3 install llvmlite numba --upgrade
  - pip3 install dabest
  - python3 setup.py develop test
