version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      # Whatever you want to do
      - run:
          name: "overview"
          command: ls && pwd
      - run:
          name: "Install Deps"
          command: sudo apt-get update && sudo apt-get install -y python3 python3-pip
      - run:
          name: "pip install dependencies (0)"
          command: pip3 install dabest
      - run:
          name: "pip install dependencies (1)"
          command: pip3 install numpy pandas --upgrade
      - run:
          name: "pip install dependencies (2)"
          command: pip3 install ms_peak_picker wheezy.template
      - run:
          name: "pip install dependencies (3)"
          ´: pip3 install Cython --upgrade
      -run:
          name: "pip install dependencies (4)"
                    ´: pip3 install Cython --upgrade
: sudo apt-get install -y python3-llvmlite
      - run:
          name: "pip install dependencies (5)"
          command: pip3 install numba --upgrade
      - run:
          name: "Setup Project"
          command: python3 setup.py develop test
      - run:
          name: "Test Project"
          command: python3 -c "from pimz import IMZMLExtract"
