version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      # Whatever you want to do
      - run:
          name: "overview"
          command: ls && pwd
      - run:
          name: "Install Deps"
          command: sudo apt-get update && sudo apt-get install -y python3 python3-pip zlib1g-dev libhdf5-serial-dev pkg-config
      - run: 
          name: "pip install dependencies (-1)"
          command: sudo pip3 install packaging fuzzy-c-means upsetplot joblib
      - run: 
          name: "pip install dependencies (0)"
          command: sudo pip3 install dabest
      - run:
          name: "pip install dependencies (1)"
          command: sudo pip3 install numpy==1.24 pandas --upgrade
      - run:
          name: "pip install dependencies (2)"
          command: sudo pip3 install ms_peak_picker wheezy.template
      - run:
          name: "pip install dependencies (3)"
          command: sudo pip3 install pybaselines numba llvmlite Cython --upgrade
      - run:
          name: "Setup Project"
          command: sudo python3 setup.py develop test
      - run:
          name: "Test Project"
          command: python3 -c "from pIMZ.imzml import IMZMLExtract"
